# Development Configuration

# Database Configuration
database:
  host: "localhost"
  port: 3306
  username: "dev_user"
  password: "dev_password"
  database: "crow_development"

# Server Configuration
server:
  host: "127.0.0.1"
  port: 3000
  threads: 4
